# Generated by Django 3.1.2 on 2020-11-03 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default='Event Title', max_length=200)),
                ('event_location', models.CharField(max_length=200)),
                ('event_details', models.TextField()),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_status', models.CharField(default='ACTIVE', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a game genre (e.g. Science Fiction)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameplanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_dateofbirth', models.DateField(blank=True, null=True)),
                ('user_bio', models.TextField(default='A simple bio')),
                ('event_attending', models.ManyToManyField(blank=True, related_name='attending', to='gameplanapp.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('game_genre', models.ManyToManyField(blank=True, to='gameplanapp.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameplanapp.game'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplanapp.gameplanuser'),
        ),
    ]
