# Generated by Django 3.1.2 on 2020-10-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplanuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='gameplanuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='gameplanuser',
            name='last_name',
        ),
    ]
