# Generated by Django 3.1.2 on 2020-10-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplanapp', '0002_auto_20201018_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_game',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameplanapp.game'),
        ),
    ]
