# Generated by Django 3.1.2 on 2020-10-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplanapp', '0003_event_event_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(default='ACTIVE', max_length=200),
        ),
    ]
