# Generated by Django 3.1.2 on 2020-10-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplanapp', '0004_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplanapp.gameplanuser'),
        ),
    ]
